"""Short, bilingual explanations for the desktop's actions and scientific terms."""

# Keep translations together so an added control cannot silently lack a language.
_MESSAGES = (
    ("help_prepare", "没有结构文件时，从合金成分准备 CIF（记录晶体中原子位置的文件）。点击打开填写窗口，生成的文件可再加入分析。", "Prepare CIFs, files describing atom positions in a crystal, when you have none. Open the form, generate starting files, then add them for analysis."),
    ("help_language", "选择中文或英文，立即切换界面和提示语言；已填写的设置会保留。", "Choose Chinese or English to change the interface and help immediately. Your settings are retained."),
    ("help_tab_local", "用电脑上的 CIF 结构文件计算可能出现的衍射峰。点击切换到文件列表和计算设置。", "Calculate expected diffraction peaks from CIF structure files on your computer. Open this tab to choose files and calculation settings."),
    ("help_tab_mp", "从 Materials Project 材料数据库查找结构并计算衍射峰。需要联网和该网站的访问密钥。", "Find structures in the Materials Project materials database and calculate expected peaks. Requires internet access and a website access key."),
    ("help_tab_results", "查看最近一次完成的计算：图谱、峰的位置和问题说明。先完成计算，这里才会有结果。", "View the latest completed calculation: its pattern, peak positions, and problem details. Run a calculation first to populate this tab."),
    ("help_input_list", "这里列出待计算的结构文件或文件夹。单击选择；按住 Ctrl 可多选，按 Delete 只移出列表，不删除原文件。", "These files or folders will be calculated. Click to select, hold Ctrl for multiple items, or press Delete to remove them from the list without deleting source files."),
    ("help_input_drop", "用下方“添加”按钮选择 CIF（记录原子位置的结构文件）或文件夹；支持拖放时也可拖到这里。", "Use the Add buttons to choose CIF files describing atom positions, or folders. You can also drop them here when drag and drop is available."),
    ("help_add_cif", "选择一个或多个 CIF（晶体结构文件），加入待计算列表；此时还不会开始计算。", "Choose one or more CIF crystal structure files to add to the calculation list. Calculation does not start yet."),
    ("help_add_folder", "选择含 CIF 结构文件的文件夹。计算时读取其中的文件；要包含下层文件夹，请勾选“扫描子文件夹”。", "Choose a folder containing CIF structure files. Its files are read when calculation starts; enable Scan subfolders to include nested folders."),
    ("help_remove", "先选择列表中的项目，再点击移出待计算列表。原文件保留在电脑上。", "Select items in the list, then click to remove them from this calculation. Source files stay on your computer."),
    ("help_clear_inputs", "移出列表中的所有输入，同时清除为它们填写的弹性数据；原文件保留。", "Remove all inputs and their manually supplied stiffness data from this list. Source files are retained."),
    ("help_output_path", "填写本次结果文件夹的完整位置，例如 D:/results/run-01。计算会把表格、说明和所选图件保存到这里。", "Enter the full folder path for this run, for example D:/results/run-01. Tables, notes, and selected figures will be saved here."),
    ("help_output_browse", "打开文件夹选择窗口，选定结果保存位置；不会立即写入文件。", "Open the folder picker to choose where results will be saved. No files are written yet."),
    ("help_recursive", "勾选后也读取所选文件夹内各层子文件夹的 CIF。关闭时只读取该文件夹直接包含的文件。", "Include CIFs in every nested subfolder of selected folders. When off, only files directly inside each selected folder are read."),
    ("help_overwrite", "勾选后，重新计算可替换该位置已有的完整结果包。程序会先检查已有文件；普通文件夹或损坏的结果不能强行覆盖。", "Allow recalculation to replace a complete existing result bundle at this path. Existing files are checked first; ordinary folders or damaged bundles cannot be forced over."),
    ("help_elasticity", "勾选后，用材料抵抗拉伸、剪切的数据计算各方向的拉伸刚度。数据须与结构文件使用相同的坐标方向；缺失或方向不匹配时显示“—”。", "Use resistance-to-stretching and shearing data to calculate stiffness in each direction. Data axes must match the structure's axes; missing or mismatched data displays —."),
    ("help_elasticity_local", "勾选后读取结构旁配套的弹性数据文件，也可用下方手动数据替代，用于计算拉伸刚度。数据坐标须与结构一致；无法计算时显示“—”。", "Read matching stiffness-data files beside the structures, or use manual values below, to calculate stretching stiffness. Data axes must match the structure; unavailable values display —."),
    ("help_elasticity_mp", "勾选后从数据库获取电脑计算的抗变形数据，用于计算拉伸刚度。只有数据与结构的坐标方向匹配时才计算；不匹配或缺失时显示“—”。", "Fetch computer-calculated resistance-to-deformation data from the database to calculate stretching stiffness. Calculation requires matching data and structure axes; missing or mismatched data displays —."),
    ("help_excel", "勾选后把峰表和来源说明另存为 Excel 工作簿，便于查看和筛选。关闭时仍保存基本结果文件。", "Also save peak tables and source notes as an Excel workbook for browsing and filtering. Basic result files are still saved when off."),
    ("help_lab_views", "在 Excel 中增加便于查峰、按原子层间距排序和查看空间对称关系的表。先勾选“写入 Excel”才能使用。", "Add Excel sheets for looking up peaks, sorting by atomic plane spacing, and checking symmetry. Enable Write Excel first."),
    ("help_patterns", "勾选后把离散的峰连成模拟曲线，并保存逐点数据；峰宽和步长设置会用于这条曲线。", "Build simulated curves from the individual peaks and save their point-by-point data. Peak width and point spacing control these curves."),
    ("help_figures", "勾选后额外保存每个结构的图谱文件；图中横轴始终是散射角 2θ，单位为度。", "Also save pattern figure files for each structure. Figure axes always use the scattering angle 2θ in degrees."),
    ("help_run_local", "先添加结构文件并选择结果位置，再点击计算。完成后自动显示图谱和峰表；这是理论参考，不能单凭它确认样品成分。", "Add structure files and choose an output folder, then calculate. Patterns and peak tables appear when finished. These are theoretical references, not proof of sample composition."),
    ("help_mp_composition", "填写元素组合，如 Ti-Al-V，或数据库结构编号，如 mp-23。只填编号时选择“指定 MP 编号”；查找结果不代表样品含有这些相。", "Enter elements such as Ti-Al-V, or database structure IDs such as mp-23. For IDs alone, choose Explicit MP IDs. Search results do not identify phases in your sample."),
    ("help_api_key", "粘贴 Materials Project 网站提供的访问密钥，用于连接材料数据库。本窗口不把密钥写入文件。", "Paste the access key provided by the Materials Project website to connect to its materials database. This window does not save the key to a file."),
    ("help_show_key", "勾选后显示已输入的访问密钥，便于核对；取消勾选恢复遮挡。", "Reveal the access key you entered so you can check it. Uncheck to hide it again."),
    ("help_mp_mode", "选择查找结构的范围。展开列表查看每种查找方式的说明，再选择适合当前输入的一项。", "Choose the scope of the structure search. Open the list for an explanation of each method, then choose one matching your input."),
    ("help_mp_limit", "必填正整数，如 50，限制最多保留多少个候选结构。超过时按排序截取前面这些结构；数量越多，下载和计算通常越久。", "Enter a positive whole number such as 50 to limit retained candidate structures. Excess candidates are cut after ranking; more candidates generally take longer to download and calculate."),
    ("help_e_hull", "限制比相同元素比例下最稳定材料组合多出的计算能量，越小越接近稳定。eV/atom 是每原子的电子伏特能量。“接近稳定”留空用 0.05；明确编号不受此筛选。", "Limit calculated energy above the most stable combination at the same composition. eV/atom means electronvolts per atom. Near stable uses 0.05 when blank; explicit IDs bypass this filter."),
    ("help_subsystem_order", "组合搜索中，每组最多包含几种元素。例如 Ti-Al-V 填 2，只查单元素和两元素组合；留空允许所有组合。只查完整元素组或指定编号时不使用。", "For combination searches, limit elements per group. Ti-Al-V with 2 searches single- and two-element groups; blank allows all combinations. Whole-group and explicit-ID searches ignore this."),
    ("help_per_subsystem", "限制每一种元素组合保留的结构数，例如 10；留空不限制。此项在合并所有候选前生效。", "Limit structures kept for each element combination, for example 10. Blank means no per-group limit; this is applied before all candidates are combined."),
    ("help_deprecated", "元素搜索时也保留数据库标记为不再推荐的旧记录；通常保持关闭。明确填写的结构编号会直接查找，不受此项筛选。", "Include older, no-longer-recommended database records in element searches; usually leave off. Explicit structure IDs are looked up directly and bypass this filter."),
    ("help_conventional", "把下载的原子重复单元转成便于阅读对称关系的常规晶胞，原子排布不变。取消勾选时需关闭弹性计算，否则不能开始。", "Convert downloaded repeating atom cells to conventional cells with clearer symmetry, without changing the atomic arrangement. If unchecked, disable elasticity before starting."),
    ("help_run_mp", "填写元素或结构编号、访问密钥和结果位置，再点击联网查找、下载并计算。完成后显示可用结构的图谱，失败项目可在问题页查看。", "Enter elements or structure IDs, an access key, and an output folder, then search, download, and calculate. View available patterns and any failed items when finished."),
    ("help_load_parameters", "选择已保存的分析设置，更新两个分析页的射线、扫描、模拟曲线和导出等共同设置。路径、密钥、数据库查询条件和手动弹性数据需另填。", "Load saved analysis settings for both tabs: radiation, scan, simulated curves, exports and subfolder scanning. Paths, keys, database search conditions and manual stiffness data are separate."),
    ("help_save_parameters", "保存射线、扫描、模拟曲线、导出和扫描子文件夹设置，下次可导入。路径、密钥、数据库查询条件和手动弹性数据不保存在这个文件中。", "Save radiation, scan, curve, export and subfolder-scanning settings for reuse. This file excludes paths, keys, database search conditions and manual stiffness data."),
    ("help_energy_shortcut", "选择常用射线条件，会一起填写输入方式和能量或波长。选“自定义”后可按自己的仪器条件填写。", "Choose a common radiation setting to fill in its input method and energy or wavelength. Choose Custom to enter your instrument's settings."),
    ("help_input_mode", "选择用射线源、能量或波长描述 X 射线。能量与波长之间切换会换算数值；固定射线源切到自定义后需重新填写波长。", "Describe X-rays by source, energy, or wavelength. Energy and wavelength values are converted when switching; changing a fixed source to Custom requires a new wavelength."),
    ("help_source_preset", "按仪器所用靶材选择 X 射线源，例如铜靶 Cu Kα；程序使用对应波长计算峰的位置。自定义时需填写波长。", "Choose the source matching your instrument's target, for example copper Cu Kα. Its wavelength determines peak positions; Custom requires a wavelength."),
    ("help_radiation", "填写仪器的 X 射线能量或波长，必须大于 0。keV 是能量单位；Å 是长度单位，1 Å = 0.1 纳米。", "Enter your instrument's X-ray energy or wavelength, greater than zero. keV is an energy unit; Å is a length unit, with 1 Å = 0.1 nanometres."),
    ("help_radiation_energy", "填写仪器的 X 射线能量，例如 30，单位 keV（千电子伏，一种能量单位）。程序由它换算波长并计算峰的位置。", "Enter the instrument's X-ray energy, for example 30 keV. keV means kiloelectronvolts, an energy unit; the program converts it to wavelength to calculate peak positions."),
    ("help_radiation_wavelength", "填写仪器的 X 射线波长，例如 1.5406，单位 Å（1 Å = 0.1 纳米）。波长会决定同一结构的峰出现在哪个角度。", "Enter the instrument's X-ray wavelength, for example 1.5406 Å. 1 Å = 0.1 nanometres; wavelength determines the angles of a structure's peaks."),
    ("help_scan_min", "填写计算的起始散射角，单位为度。2θ 表示入射射线与散射射线的夹角；小于此角度的峰不计入。", "Enter the starting scattering angle in degrees. 2θ is the angle between incoming and scattered X-rays; peaks below this angle are excluded."),
    ("help_scan_max", "填写计算的结束散射角，单位为度，须大于起始角且不超过 180。大于此角度的峰不计入。", "Enter the ending scattering angle in degrees, greater than the start and at most 180. Peaks above it are excluded."),
    ("help_step", "填写模拟曲线上相邻数据点相隔多少度，例如 0.02。越小越细，但计算点数和文件大小也会增加。", "Set the angle between adjacent points in the simulated curve, for example 0.02 degrees. Smaller spacing adds detail, more points, and larger files."),
    ("help_fwhm", "设置模拟峰有多宽：FWHM 是峰在一半高度处的宽度，单位为度。比如 0.15；调大后峰更宽，峰的位置不变。", "Set the simulated peak width: FWHM means its width at half height, in degrees, for example 0.15. Larger values broaden peaks without moving them."),
    ("help_eta", "设置混合峰形中长尾部分的比例，填 0 到 1。0 是钟形峰，1 是长尾峰；只在选择混合峰形时使用。", "Set the long-tail share of the mixed peak shape, from 0 to 1. 0 is bell-shaped and 1 is long-tailed; used only for the mixed shape."),
    ("help_d_min", "只保留原子层间距不小于此值的峰；填正数，单位 Å（0.1 纳米）。d 就是重复原子层之间的距离；留空不设下限。", "Keep peaks with atomic plane spacing at least this value. Enter a positive number in Å (0.1 nanometres). d is the distance between repeating planes; blank means no lower limit."),
    ("help_d_max", "只保留原子层间距不大于此值的峰；填正数，单位 Å（0.1 纳米），且大于下限。留空不设上限。", "Keep peaks with atomic plane spacing at most this value. Enter a positive number in Å (0.1 nanometres), greater than the lower limit. Blank means no upper limit."),
    ("help_profile_model", "选择模拟峰的外形，决定峰周围曲线的形状；不会改变峰的位置。展开列表可查看各形状的区别。", "Choose the simulated peak shape, which controls the surrounding curve without moving peak positions. Open the list to compare shapes."),
    ("help_pattern_axis", "选择曲线数据横坐标的表示方式：角度或原子层间距及其倒数。只改变 CSV/Excel 曲线数据，界面和导出图仍使用角度。", "Choose curve-data coordinates: angle, atomic plane spacing, or inverse spacing. This changes CSV/Excel curve data; on-screen and exported figures still use angle."),
    ("help_profile_points", "设置一次模拟曲线最多计算多少个点，须为正整数。超限会停止并提示；可增大步长或缩小角度范围来减少点数。", "Set the maximum number of points in a simulated curve, as a positive whole number. Exceeding it stops with a message; increase spacing or narrow the angle range to reduce points."),
    ("help_reflection_estimate", "设置寻找衍射峰时最多检查多少组原子层方向，须为正整数。超限会停止，避免大结构占用过多时间和内存。", "Set the maximum estimated number of plane directions checked while finding peaks, as a positive whole number. Exceeding it stops to avoid excessive time and memory use."),
    ("help_details_profile", "点击展开或收起模拟峰宽、数据点间隔和原子层间距筛选设置。收起后已填写的值仍会使用。", "Show or hide peak-width, point-spacing, and atomic plane spacing filters. Values remain in use when the section is collapsed."),
    ("help_details_candidates", "点击展开或收起候选数量、计算能量和旧数据库记录的筛选条件。收起后条件仍会生效。", "Show or hide candidate-count, calculated-energy, and old-record filters. Their settings still apply when collapsed."),
    ("help_resource_guards", "点击展开或收起计算规模上限。超过上限时会停止并说明原因，避免一次计算过大。", "Show or hide calculation size limits. Oversized calculations stop with an explanation instead of using excessive resources."),
    ("help_details_cij", "点击展开或收起手动弹性数据。先在文件列表选择结构，再给它填写材料拉伸或剪切时的刚度。", "Show or hide manual stiffness data. Select structures in the file list first, then enter their resistance to stretching or shearing."),
    ("help_cij", "Cij 是描述材料拉伸和剪切刚度的数值，单位 GPa（十亿帕）。请使用可靠来源的数据；关闭弹性计算只暂停使用，填写值仍保留。", "Cij values describe resistance to stretching and shearing, in GPa (billion pascals). Use reliable source data; turning elasticity off retains the values for later use."),
    ("help_c11", "C11 描述沿晶体坐标轴拉伸时的刚度，单位 GPa（十亿帕）。填入立方晶体的已知数值，再点击“应用立方”。", "C11 is stiffness when stretched along a crystal coordinate axis, in GPa (billion pascals). Enter a known cubic-crystal value, then click Apply cubic."),
    ("help_c12", "C12 描述沿一条轴拉伸时另一条轴的响应，单位 GPa（十亿帕）。与 C11、C44 一起用于立方晶体。", "C12 describes the response along one axis to stretching along another, in GPa (billion pascals). It is used with C11 and C44 for cubic crystals."),
    ("help_c44", "C44 描述晶体剪切变形时的刚度，单位 GPa（十亿帕）。与 C11、C12 一起用于立方晶体。", "C44 is resistance to shear deformation, in GPa (billion pascals). It is used with C11 and C12 for cubic crystals."),
    ("help_apply_cubic", "先选文件，再用三个数值生成立方晶体的抗变形表，供选中结构下次计算使用。只在当前窗口暂存，退出后需重新填；原文件不变。", "Select files, then build a cubic stiffness table from the three values for their next calculation. Values last only in this window; source files stay unchanged."),
    ("help_cij_paste", "粘贴 6 行、每行 6 个数值，单位 GPa（十亿帕）。行列顺序均为 11、22、33、23、13、12：前三项沿三条轴拉伸，后三项剪切。数字用空格或逗号隔开，再点“应用矩阵”。", "Paste six rows of six values in GPa (billion pascals), separated by spaces or commas. Rows and columns follow 11,22,33,23,13,12: three stretching axes, then three shearing pairs. Click Apply matrix."),
    ("help_apply_matrix", "先选文件，再检查 6×6 抗变形表；对角线两侧对应值不一致时会取平均并提示。只在当前窗口暂存，原文件不变；修改文本本身不会应用。", "Select files, then check the 6×6 stiffness table. Unequal values mirrored across the diagonal are averaged with a warning. Values stay in this window; editing text alone does not apply them."),
    ("help_clear_cij", "清除选中 CIF 的手动弹性数据；有文件夹被选中时不能清除。未选择任何项目时清除全部手动数据，原文件不变。", "Clear manual stiffness data for selected CIFs; selecting a folder blocks clearing. With no items selected, clear all manual data. Source files are unchanged."),
    ("help_copy_log", "复制当前窗口的全部运行记录到剪贴板，便于粘贴给他人查看问题。", "Copy all activity messages to the clipboard so you can paste them when discussing a problem."),
    ("help_clear_log", "清空窗口里显示的运行记录；已保存的计算结果和文件不会删除。", "Clear activity messages from this window. Saved calculation results and files are retained."),
    ("help_log", "这里显示计算进度和问题说明。滚动查看旧记录；可用上方“复制”按钮复制全部内容。", "Read progress and problem messages here. Scroll for earlier messages, or use Copy above to copy them all."),
    ("help_resize_log", "拖动这条分隔线，调整上方工作区和下方运行记录各占多少空间。", "Drag this divider to change how much space the work area and activity log each receive."),
    ("help_scrollbar", "拖动滑块查看当前区域中未显示的内容；滚动不会改变已填写的设置。", "Drag the thumb to see more content in this area. Scrolling does not change your settings."),
    ("help_table_resize", "拖动两列之间的边界，调宽或调窄这一列，查看被遮住的内容。", "Drag the edge between columns to make this column wider or narrower and reveal hidden content."),
    ("help_preview_excel", "完成并生成 Excel 后，点击用电脑上的表格软件打开临时副本。编辑副本不会改动结果包；改过的副本会保留。", "After Excel output is generated, open a temporary copy in your spreadsheet app. Editing the copy leaves the result bundle intact; edited copies are retained."),
    ("help_save_excel", "完成并生成 Excel 后，选择位置另存一份工作簿，方便编辑或分享。结果包中的原工作簿保留。", "After Excel output is generated, save a workbook copy to a location you choose for editing or sharing. The original in the result bundle is retained."),
    ("help_open_folder", "计算完成后，点击在文件管理器中打开结果文件夹，查看已保存的表格、说明和图件。", "After calculation, open the result folder in your file manager to view the saved tables, notes, and figures."),
    ("help_compat", "打开保留的独立工作台，可分别导出峰表或下载结构文件。点击子菜单选择要打开的窗口。", "Open a retained standalone workbench for peak-table export or structure downloads. Choose a window from this submenu."),
    ("help_compat_peaks", "打开独立峰表导出窗口：选择结构文件，保存 Excel 峰表和所选图件。主窗口已填写的内容会保留。", "Open the standalone exporter to save Excel peak tables and selected figures from structure files. Inputs in this main window are retained."),
    ("help_compat_download", "打开独立下载窗口：按材料数据库编号或元素组合搜索、下载 CIF 结构文件。需要联网和访问密钥。", "Open the standalone downloader to search by database ID or element combination and download CIF structure files. Requires internet and an access key."),
    ("help_choice_source", "按仪器的 X 射线靶材选择；程序自动使用该射线源的波长。", "Choose the instrument's X-ray target; the program uses that source's wavelength automatically."),
    ("help_choice_energy", "直接填写 X 射线能量，单位 keV；程序换算成波长后计算。", "Enter X-ray energy in keV; the program converts it to wavelength for calculation."),
    ("help_choice_wavelength", "直接填写 X 射线波长，单位 Å（0.1 纳米）。", "Enter X-ray wavelength directly in Å (0.1 nanometres)."),
    ("help_choice_Cu", "铜靶的常用 X 射线，波长约 1.5406 Å；选择后自动填写。", "Common copper-target X-rays, about 1.5406 Å; choosing this fills the value automatically."),
    ("help_choice_Co", "钴靶的常用 X 射线，波长约 1.7890 Å；选择后用于计算峰的位置。", "Common cobalt-target X-rays, about 1.7890 Å; used to calculate peak positions."),
    ("help_choice_Fe", "铁靶的常用 X 射线，波长约 1.9360 Å；选择后用于计算峰的位置。", "Common iron-target X-rays, about 1.9360 Å; used to calculate peak positions."),
    ("help_choice_Mo", "钼靶的常用 X 射线，波长约 0.7107 Å；选择后用于计算峰的位置。", "Common molybdenum-target X-rays, about 0.7107 Å; used to calculate peak positions."),
    ("help_choice_Ag", "银靶的常用 X 射线，波长约 0.5594 Å；选择后用于计算峰的位置。", "Common silver-target X-rays, about 0.5594 Å; used to calculate peak positions."),
    ("help_choice_30", "使用 30 keV 的 X 射线能量，选择后自动切换到能量输入并填写 30。", "Use X-rays at 30 keV; choosing this switches to energy input and fills in 30."),
    ("help_choice_83", "使用 83 keV 的 X 射线能量，选择后自动切换到能量输入并填写 83。", "Use X-rays at 83 keV; choosing this switches to energy input and fills in 83."),
    ("help_choice_custom", "使用自己仪器的数值；按选定的能量或波长输入方式填写，射线源自定义时填写波长。", "Use your own instrument's value in the selected energy or wavelength mode. A custom source requires a wavelength."),
    ("help_choice_mixed", "混合峰形：把钟形和长尾形按比例相加；用 η 设置长尾部分的比例。", "Mixed peak shape: combine bell-shaped and long-tailed peaks. η sets the long-tail share."),
    ("help_choice_gaussian", "高斯峰形：像钟形，离峰中心越远越快下降。选择后模拟曲线使用这种外形。", "Gaussian shape: a bell-shaped peak that falls quickly away from its centre. The simulated curve uses this shape."),
    ("help_choice_lorentzian", "洛伦兹峰形：峰两侧下降较慢，尾部较长。选择后模拟曲线使用这种外形。", "Lorentzian shape: a peak that falls more slowly on either side, with longer tails. The simulated curve uses this shape."),
    ("help_choice_two_theta", "2θ 是入射与散射 X 射线的夹角；曲线数据横坐标用度表示。", "2θ is the angle between incoming and scattered X-rays. Curve-data coordinates are in degrees."),
    ("help_choice_d", "d 是重复原子层之间的距离；曲线数据横坐标用 Å（0.1 纳米）表示。", "d is the distance between repeating atomic planes. Curve-data coordinates use Å (0.1 nanometres)."),
    ("help_choice_q", "q 把原子层间距 d 换算成另一种峰位置：q=2π/d。单位 Å⁻¹ 表示每埃；间距越小，q 越大。", "q expresses peak position as q=2π/d, where d is atomic plane spacing. Å⁻¹ means per ångström; smaller spacing gives larger q."),
    ("help_choice_g", "g 是原子层间距 d 的倒数：g=1/d。单位 Å⁻¹ 表示每埃；间距越小，g 越大。", "g is inverse atomic plane spacing: g=1/d. Å⁻¹ means per ångström; smaller spacing gives larger g."),
    ("help_choice_possible", "查找输入元素的各种组合。例如 Ti-Al 会同时查 Ti、Al 和 Ti-Al 的结构；不能据此确认样品含有它们。", "Search combinations of the entered elements. Ti-Al searches Ti, Al, and Ti-Al structures; this does not establish that your sample contains them."),
    ("help_choice_near_stable", "查找各种元素组合，保留计算能量接近相同成分比例下最稳定组合的结构。能量上限留空时用每原子 0.05 电子伏。", "Search element combinations and retain structures close in calculated energy to the most stable combination at the same composition. Blank uses 0.05 electronvolts per atom."),
    ("help_choice_single", "只查包含全部输入元素的组合。例如 Ti-Al 只查 Ti-Al，不另查纯 Ti 或纯 Al。", "Search only the complete entered element combination. Ti-Al searches Ti-Al, without separate pure Ti or pure Al searches."),
    ("help_choice_mpids", "只按明确填写的数据库编号（如 mp-23）查找结构，不查其他元素组合。再点击运行，程序才会下载并计算。", "Find only the database IDs you entered, such as mp-23, without searching element combinations. Click Run to download and calculate them."),
    ("help_result_path", "这是本次结果所在的文件夹。可选中文本后复制路径；要查看文件，点击底部“打开结果文件夹”。", "This is the current result folder. Select and copy the path, or use Open result folder at the bottom to view its files."),
    ("help_result_phase", "选择一个已算出的结构（相是原子排布不同的一种材料结构）。图谱和峰表会一起切换，问题列表仍显示本次全部记录。", "Choose a calculated structure; a phase is a distinct atomic arrangement. The pattern and peaks switch together; problem records still cover the whole run."),
    ("help_result_pattern", "横轴 2θ 是散射角（度），纵轴比较本结构各峰高低，最高记为 100；不代表样品中该相的含量。在峰表选中一行后可定位到图中。", "2θ is scattering angle in degrees. Heights compare this structure's peaks, with the highest set to 100; they are not sample phase percentages. Locate a selected table row here."),
    ("help_result_peaks", "查看每个理论峰的位置和强度。点击列名排序；双击一行或选中后按 Enter，可在图谱中定位该峰。", "View each theoretical peak's position and strength. Click a column heading to sort; double-click a row or select it and press Enter to locate the peak on the pattern."),
    ("help_result_diagnostics", "查看本次计算的提醒和失败原因。选择一条记录，下方会显示完整说明；有提醒不一定代表计算失败。", "Read reminders and failure reasons for this run. Select a record for its full explanation below; a warning does not necessarily mean calculation failed."),
    ("help_result_previous", "查看峰表的上一页，每页最多 250 行。第一页时此按钮不可用。", "View the previous page of the peak table, with up to 250 rows per page. Unavailable on the first page."),
    ("help_result_next", "查看峰表的下一页，每页最多 250 行。最后一页时此按钮不可用。", "View the next page of the peak table, with up to 250 rows per page. Unavailable on the last page."),
    ("help_result_locate", "先在峰表选中一行，再点击切换到图谱，标出该峰的角度和原子层方向编号。", "Select a peak-table row, then switch to the pattern and mark its angle and atomic plane direction numbers."),
    ("help_diag_filter", "只查看选定类型的问题记录；筛选不会删除记录，也不会改变计算结果。", "Show only the selected type of problem record. Filtering does not delete records or change calculation results."),
    ("help_diag_all", "显示本次计算的全部记录，包括普通信息、需要留意的提醒和失败原因。", "Show all records from this calculation, including information, warnings and failure reasons."),
    ("help_diag_warning", "只显示需要留意的提醒；对应结构可能仍有可用结果。", "Show warnings that need attention; affected structures may still have usable results."),
    ("help_diag_error", "只显示导致部分操作或结构失败的错误；选择记录查看具体原因。", "Show errors that caused an operation or structure to fail. Select a record to read the reason."),
    ("help_diag_details", "选中问题后，这里显示完整原因及发生位置。可滚动阅读，也可选中文字后复制。", "Select a problem to read its full cause and location here. Scroll to read more, or select text to copy it."),
    ("help_peak_hkl", "h、k、l 是标记晶体中一组原子层方向的三个整数。点击列名按这些编号排序，再点反向排序。", "h, k, l are three whole numbers identifying a set of atomic planes in a crystal. Click to sort by these numbers; click again to reverse."),
    ("help_peak_angle", "2θ 是这个峰对应的散射角，单位为度。点击按角度从小到大排序，再点反向排序。", "2θ is this peak's scattering angle in degrees. Click to sort from smaller to larger angles; click again to reverse."),
    ("help_peak_d", "d 是该峰对应的重复原子层间距，单位 Å（1 Å = 0.1 纳米）。点击按间距排序，再点反向排序。", "d is the peak's atomic plane spacing in Å (1 Å = 0.1 nanometres). Click to sort by spacing; click again to reverse."),
    ("help_peak_intensity", "相对强度用于比较同一结构各峰的高低；最强峰记为 100，不是样品中该相的百分含量。点击排序，再点反向排序。", "Relative intensity compares peak heights within this structure; the strongest peak is 100, not a phase percentage in the sample. Click to sort; click again to reverse."),
    ("help_peak_q", "q=2π/d，用原子层间距 d 表示峰的位置，单位 Å⁻¹（每埃）。点击按数值排序，再点反向排序。", "q=2π/d expresses peak position using atomic plane spacing d, in Å⁻¹ (per ångström). Click to sort by value; click again to reverse."),
    ("help_peak_modulus", "杨氏模量 E(hkl)：垂直于这组原子层拉伸时抵抗变形的能力，单位 GPa（十亿帕）。“—”表示没有可用且坐标匹配的数据；点击排序，再点反向。", "Young's modulus E(hkl): resistance to stretching normal to these atomic planes, in GPa (billion pascals). — means no usable data with matching axes. Click to sort; click again to reverse."),
    ("help_diag_level", "信息是普通记录，提醒表示需要留意，错误表示某项操作失败。点击一条记录，下方显示具体原因。", "Information is a routine record; warnings need attention; errors mean an operation failed. Select a record to read the specific reason below."),
    ("help_diag_source", "指出问题发生在哪个步骤、文件或结构。点击对应记录查看完整说明。", "Shows the step, file, or structure where a problem occurred. Select its record to read the full explanation."),
    ("help_cifs_composition", "填写合金包含的元素，用连字符分开，例如 Ti-Al-V。元素含量在下方按牌号或百分比填写。", "Enter the alloy's elements separated by hyphens, for example Ti-Al-V. Enter their amounts below using a grade or percentages."),
    ("help_cifs_nominal", "按常用牌号生成起始成分；目前支持 TC4、Ti64 和 Ti-6Al-4V，都代表钛中约 6% 铝、4% 钒（按质量）。", "Use a common grade for starting composition. TC4, Ti64, and Ti-6Al-4V are supported, all representing titanium with about 6% aluminium and 4% vanadium by mass."),
    ("help_cifs_weight", "按质量填写每种元素占合金的百分比；例如每 100 克含 Ti 90 克、Al 6 克、V 4 克。", "Enter each element's percentage by mass, for example 90 g Ti, 6 g Al, and 4 g V in every 100 g of alloy."),
    ("help_cifs_atomic", "按原子数填写各元素百分比；例如每 100 个原子中有 Ti 86 个、Al 10 个、V 4 个。", "Enter each element's percentage by atom count, for example 86 Ti, 10 Al, and 4 V atoms in every 100 atoms."),
    ("help_cifs_percent_weight", "填写所有元素的质量百分比，合计 100；格式如 Ti=90,Al=6,V=4。这些数值用于生成起始结构的成分。", "Enter all mass percentages, totalling 100, such as Ti=90,Al=6,V=4. These amounts set the starting structure's composition."),
    ("help_cifs_percent_atomic", "填写所有元素的原子数百分比，合计 100；格式如 Ti=86,Al=10,V=4。不是各元素的重量比例。", "Enter all atom-count percentages, totalling 100, such as Ti=86,Al=10,V=4. These are not weight percentages."),
    ("help_cifs_host", "可填写用来建立原子排布的主要元素，例如 Ti。留空时选含量最多的元素；若最高含量并列，需要手动指定。", "Optionally enter the main element whose atom arrangement is used, for example Ti. Blank chooses the largest fraction; tied largest fractions require a choice."),
    ("help_cifs_output", "填写一个尚不存在的新文件夹，生成的结构和报告会保存其中。已有文件夹不能用于本次准备。", "Enter a new folder that does not yet exist. Generated structures and reports will be saved there; existing folders cannot be used."),
    ("help_cifs_parent", "选择新结果文件夹的上一级位置；保留当前填写的文件夹名称。开始准备后才创建文件夹。", "Choose the parent location for the new result folder, keeping its currently entered name. The folder is created when preparation starts."),
    ("help_cifs_alpha", "勾选后生成 α 相起始文件：钛原子按六角形重复单元排列。生成模型不代表样品中已确认存在此相。", "Prepare an α starting file with titanium atoms in a hexagonal repeating cell. This model does not confirm that the phase exists in your sample."),
    ("help_cifs_beta", "勾选后生成 β 相起始文件：钛原子按立方体顶点和中心排列。生成模型不代表样品中已确认存在此相。", "Prepare a β starting file with titanium atoms at cube corners and the centre. This model does not confirm that the phase exists in your sample."),
    ("help_cifs_alpha_double_prime", "勾选后生成 α″ 起始文件，原子按三条互相垂直、长度不同的边排列。这种排布可在钛合金快速冷却后出现。", "Prepare an α″ starting file with three perpendicular cell edges of different lengths. This arrangement can occur after rapid cooling of titanium alloys."),
    ("help_cifs_advanced", "点击展开或收起离线模式、访问密钥、已有结构模板和文献数值设置；收起后设置仍然生效。", "Show or hide offline mode, access key, existing structure templates, and literature values. Their settings still apply when collapsed."),
    ("help_cifs_parameters", "选择为已勾选相准备的 JSON 文本数据文件；晶胞（原子排列的重复单元）尺寸和原子坐标需附出处。分析预设不能用在这里；可留空使用起始假设。", "Choose a JSON text-data file for checked phases, citing sources for cell sizes or atom coordinates. Analysis presets cannot be used here; blank uses starting assumptions."),
    ("help_cifs_parameters_browse", "选择已勾选相的文献数值 JSON 文件，不是主窗口的分析预设。只读取文件；程序不会修改它或自动查找论文。", "Choose literature-value JSON for the checked phases, not a main-window analysis preset. The file is read unchanged; the program does not search papers."),
    ("help_cifs_offline", "勾选后只使用电脑上的模板和随程序提供的结构，不连接材料数据库，也不需要访问密钥。", "Use only local templates and structures included with the program. No database connection or access key is needed."),
    ("help_cifs_api_key", "联网时填写 Materials Project 的访问密钥；留空会读取电脑已设置的 MP_API_KEY。离线时不用此值，也不会将密钥存入文件。", "For online use, enter a Materials Project access key; blank reads MP_API_KEY if set on the computer. Offline mode ignores it, and it is never saved to a file."),
    ("help_cifs_template", "可选择此相已有的 CIF 原子结构文件，作为生成模型的起点；留空使用数据库或随包结构。只用于已勾选的相，原文件不变。", "Optionally choose an existing CIF atomic structure as this phase's starting template. Blank uses a database or included structure. Only checked phases use it; the source file is retained."),
    ("help_cifs_template_browse", "选择对应相的 CIF 原子结构文件作为模板；只记录路径，不会立即生成文件。", "Choose a CIF atomic structure file as the template for this phase. This records its path without generating files yet."),
    ("help_cifs_run", "按上方成分和所选原子排布生成起始结构文件，并保存各项假设和来源说明。完成后可查看报告或载入分析。", "Generate starting structures from the composition and checked arrangements, recording assumptions and sources. Then inspect the report or load the files for analysis."),
    ("help_cifs_load", "准备完成后，把所有成功生成的结构加入主窗口的待计算列表，并切换到本地分析页；此时还不会开始计算。", "After preparation, add all successfully generated structures to the main calculation list and switch to local analysis. Calculation does not start yet."),
    ("help_cifs_report", "准备后打开报告，查看生成文件采用了哪些成分、数值、来源和假设。", "After preparation, open the report to see the composition, values, sources, and assumptions used."),
    ("help_cifs_folder", "准备后在文件管理器中打开新结果文件夹，查看生成的结构和报告。", "After preparation, open the new result folder in your file manager to view structures and reports."),
    ("help_cifs_close", "关闭此准备窗口。已生成的文件会保留；若正在准备，后台任务仍会继续写出结果。", "Close this preparation window. Generated files are retained; a running background task continues writing its results."),
    ("help_cifs_tree", "每行是一种待准备的原子排布。点击一行，下方显示文件位置和该项说明；载入按钮会加入所有成功文件。", "Each row is a requested atomic arrangement. Select a row for its path and notes below; Load adds all successful files."),
    ("help_cifs_status", "说明结构来自本地模板、数据库还是随包文件，以及是否成功生成。选择记录可查看详情。", "Shows whether the structure came from a local template, database, or included file, and whether generation succeeded. Select a row for details."),
    ("help_cifs_details", "选中上方一行后，这里显示文件位置和说明。可滚动查看，也可选中文字后复制。", "Select a row above to view its file path and notes here. Scroll to read more, or select text to copy it."),
)

HELP_TEXT = {
    "zh": {key: zh for key, zh, _en in _MESSAGES},
    "en": {key: en for key, _zh, en in _MESSAGES},
}

CONTROL_HELP = {
    "prepare_initial": "help_prepare", "btn_add_cif": "help_add_cif",
    "btn_add_folder": "help_add_folder", "btn_remove": "help_remove",
    "btn_clear": "help_clear_inputs", "scan_recursive": "help_recursive",
    "overwrite_bundle": "help_overwrite", "pair_elasticity": "help_elasticity_local",
    "eval_elasticity": "help_elasticity_mp", "write_excel": "help_excel",
    "export_lab_views": "help_lab_views", "include_patterns": "help_patterns",
    "include_figures": "help_figures", "analyze_local": "help_run_local",
    "composition": "help_mp_composition", "api_key": "help_api_key",
    "show_key": "help_show_key", "mode": "help_mp_mode",
    "max_candidates": "help_mp_limit", "e_hull_max": "help_e_hull",
    "subsystem_order": "help_subsystem_order", "per_subsystem": "help_per_subsystem",
    "include_deprecated": "help_deprecated", "conventional_cells": "help_conventional",
    "run_mp": "help_run_mp", "load_parameters": "help_load_parameters",
    "save_parameters": "help_save_parameters", "energy_shortcut": "help_energy_shortcut",
    "input_mode": "help_input_mode", "source_preset": "help_source_preset",
    "radiation_value": "help_radiation", "two_theta_min": "help_scan_min",
    "two_theta_max": "help_scan_max", "step": "help_step", "fwhm": "help_fwhm",
    "eta": "help_eta", "d_min": "help_d_min", "d_max": "help_d_max",
    "profile_model": "help_profile_model", "pattern_axis": "help_pattern_axis",
    "profile_points": "help_profile_points", "reciprocal_candidates": "help_reflection_estimate",
    "c11": "help_c11", "c12": "help_c12", "c44": "help_c44",
    "apply_cubic": "help_apply_cubic", "apply_matrix": "help_apply_matrix",
    "clear_cij": "help_clear_cij", "copy": "help_copy_log", "clear_log": "help_clear_log",
    "preview_excel": "help_preview_excel", "save_excel_as": "help_save_excel",
    "open_result_folder": "help_open_folder",
}

VARIABLE_HELP = {
    "lang_var": "help_language", "local_output": "help_output_path", "mp_output": "help_output_path",
    "mp_composition": "help_mp_composition", "mp_key": "help_api_key", "mp_mode": "help_mp_mode",
    "mp_limit": "help_mp_limit", "mp_e_hull": "help_e_hull",
    "mp_subsystem_order": "help_subsystem_order", "mp_per_subsystem": "help_per_subsystem",
    "energy_shortcut": "help_energy_shortcut", "input_mode": "help_input_mode",
    "source_preset": "help_source_preset", "radiation_value": "help_radiation",
    "two_theta_min": "help_scan_min", "two_theta_max": "help_scan_max",
    "step": "help_step", "fwhm": "help_fwhm", "eta": "help_eta",
    "d_min_A": "help_d_min", "d_max_A": "help_d_max",
    "profile_model": "help_profile_model", "pattern_axis": "help_pattern_axis",
    "max_profile_points": "help_profile_points", "max_reflection_estimate": "help_reflection_estimate",
    "cij_c11": "help_c11", "cij_c12": "help_c12", "cij_c44": "help_c44",
}

CHOICE_HELP = {
    "zh": "help_language", "en": "help_language",
    "source": "help_choice_source", "energy": "help_choice_energy", "wavelength": "help_choice_wavelength",
    "Cu Kα": "help_choice_Cu", "Cu Ka": "help_choice_Cu", "Co Ka": "help_choice_Co",
    "Fe Ka": "help_choice_Fe", "Mo Ka": "help_choice_Mo", "Ag Ka": "help_choice_Ag",
    "30 keV": "help_choice_30", "83 keV": "help_choice_83", "Custom": "help_choice_custom",
    "pseudo_voigt": "help_choice_mixed", "gaussian": "help_choice_gaussian", "lorentzian": "help_choice_lorentzian",
    "two_theta": "help_choice_two_theta", "d_spacing": "help_choice_d", "q": "help_choice_q", "g": "help_choice_g",
    "possible_phases": "help_choice_possible", "near_stable": "help_choice_near_stable",
    "single_chemsys": "help_choice_single", "mpids_only": "help_choice_mpids",
}
